"""agregar restriccion unica a calificaciones

Revision ID: 210ab8214e53
Revises: e49f3c5e787b
Create Date: 2026-09-29 18:56:09.670874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210ab8214e53'
down_revision: Union[str, Sequence[str], None] = 'e49f3c5e787b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_calificacion_alumno_materia_periodo', 'calificaciones', ['alumno_id', 'materia_id', 'periodo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ##
    op.drop_constraint('uq_calificacion_alumno_materia_periodo', 'calificaciones', type_='unique')
    # ### end Alembic commands ###
