"""agregar periodo a calificaciones

Revision ID: 605e5c5357a5
Revises: 
Create Date: 2026-09-09 20:24:15.441242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605e5c5357a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'calificaciones',
        sa.Column(
            'periodo',
            sa.Integer(),
            nullable=False,
            server_default='1'
        )
    )

    op.alter_column(
        'calificaciones',
        'periodo',
        server_default=None
    )

    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calificaciones', 'periodo')
    # ### end Alembic commands ###
