"""crear tabla inscripciones

Revision ID: 924015851034
Revises: 210ab8214e53
Create Date: 2026-09-30 16:46:01.368426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "924015851034"
down_revision: Union[str, Sequence[str], None] = "210ab8214e53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inscripciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alumno_id", sa.Integer(), nullable=False),
        sa.Column("materia_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alumno_id"],
            ["alumnos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["materia_id"],
            ["materias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "alumno_id",
            "materia_id",
            name="uq_inscripcion_alumno_materia",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inscripciones")
    # ### end Alembic commands ###
